name: Latest blog post workflow
on:
 schedule:
   # every hour
   - cron: '0 * * * *' 
 workflow_dispatch: 
jobs:
 update-readme-with-blog:
   name: Update README with latest blog posts
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: gautamkrishnar/blog-post-workflow@master
       with:
         feed_list: "https://johnbraun.blog/rss.xml"
